keys:
  - &matt-primary age1xh0jjtj4ys44pplk3yw6c06ru3fh8xdqrlrjwy0u20x8td0tqvsqzqluen
  - &xin age1m2ee7vdxgrzmda4zrndv3976cplhk37l3t7gudfjt6vgjdtume3skngvpm
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *matt-primary
        - *xin
