# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [ "quiet" ];
  boot.extraModulePackages = [ ];
  boot.plymouth.enable = true;
  #boot.initrd.systemd.enable = true;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/47197c13-0937-4b85-ae31-2b973f45f70f";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  boot.initrd.luks.devices."crypted".device =
    "/dev/disk/by-uuid/fd99a0fa-07d2-44ca-b8d4-fa5ec1f72eee";

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/47197c13-0937-4b85-ae31-2b973f45f70f";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/47197c13-0937-4b85-ae31-2b973f45f70f";
    fsType = "btrfs";
    options = [ "subvol=@varlog" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/47197c13-0937-4b85-ae31-2b973f45f70f";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/47197c13-0937-4b85-ae31-2b973f45f70f";
    fsType = "btrfs";
    options = [ "subvol=@persist" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/917F-2E16";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  #networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;
  # networking.interfaces.wwan0.useDHCP = lib.mkDefault true;
  #systemd.network.wait-online.enable = lib.mkForce false;
  #networking.tempAddresses = "enabled";
  networking.useNetworkd = false;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.steam-hardware.enable = true;
}
